"""empty message

Revision ID: bafcee725f91
Revises: 4d264dfe90e4
Create Date: 2020-06-23 00:28:17.597468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bafcee725f91'
down_revision = '4d264dfe90e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('read_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'read_count')
    # ### end Alembic commands ###
